### ISSUE TITLE
Atom classification

### ISSUE THREAD

**Issue by NRayya** [nmrML/nmrCV#16] opened 2024-03-20 20:05 UTC
In CHEBI, [atom ](https://terminology.nfdi4chem.de/ts/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_33250)appears under[ chemical entity](https://terminology.nfdi4chem.de/ts/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_24431). However [molecular entity](https://terminology.nfdi4chem.de/ts/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_23367) definition includes "Any **constitutionally** or **isotopically** distinct atom...". We need to decide were atom should go

![image](https://github.com/nmrML/nmrCV/assets/82588017/2d234b85-c130-4d74-b82a-fcb4e78afbbd)

**Comment by StroemPhi** [comment] 2024-03-21 07:12
The problem is that we should not change the hierarchy of CHEBI in our ontology, as this is bad practice. This means we have to live with this until it gets resolved in CHEBI. I don't know if there is an issue for this at CHEBI currently.

**Comment by StroemPhi** [comment] 2024-03-22 07:46
Two threads that shed some more light on why atom is not subsumed under molecular entity:
https://github.com/ebi-chebi/ChEBI/issues/688
https://github.com/EnvironmentOntology/envo/issues/977

**Comment by tilfischer** [comment] 2024-03-22 10:12
I wrote this to @StroemPhi before, but it shocking to me that we live in an ontological world before 1912. Until that point chemistry looked on atoms, ions and molecules. Consequently, Wilhelm Ostwald (Nobel price 1909) coined the unit Mol in 1983, which is one of the seven SI base units. Mineralogy was closely bound to geology at that time, but Max von Laure discovered diffraction of x-rays by crystals and received the Nobel price in 1914. The Nobel price a year later was given to Bragg and Bragg for the first crystal structure (diamond) and that what we now call Braggs-Law. Notably, Laurence Bragg was only 25 year old when he received this price and is still the youngest scientist who ever received that price. 

Since that days it came apparent that there are more complex things out there in chemistry, which are very different than the molecules scientists looked in these days. I agree that this was of modest interest to many organic chemists, but more than 100 years later, this has changed and chemists are aware of this (although, to my great regret, I know of exceptions). What is chemistry about? The properties, behaviour and transformation (reaction) of matter.

Something, for that some people would say its simply wrong or other might say this this is highly misleading, won't get better if it is repeated and repeated and over and over again.

**Comment by NRayya** [comment] 2024-04-02 18:34
> The problem is that we should not change the hierarchy of CHEBI in our ontology, as this is bad practice. This means we have to live with this until it gets resolved in CHEBI. I don't know if there is an issue for this at CHEBI currently.

Totally agree, I had to open the issue as we had the discussion. But the way I see it is that CHEBI implementation is correct as they have only a subset of atoms under molecular entity which are **constitutionally** or **isotopically** distinct atom. My understanding is they are covering the cases where "an atom serves as a molecule" such as with noble gases
<img width="552" alt="image" src="https://github.com/nmrML/nmrCV/assets/82588017/67a82f51-5f91-4984-b931-53e7c6a2e994">

**Comment by NRayya** [comment] 2024-04-02 18:42
In all cases, including only solvents and references in nmrCv might lead us not to use the atoms at all and it gets removed from nmrCV.

**Comment by StroemPhi** [comment] 2024-04-03 08:40
I just saw that a previous comment of mine was incomplete. What I wanted to write there is that, only in the case of us needing to say that e.g. 1H NMR is probing/stimulating the nuclei of H atoms in the sample, I would opt for using the atom branch. In other use cases (solvents & chemical shift reference compounds) the molecular entity branch is better. 
Reason: [CHEBI:atom](https://terminology.nfdi4chem.de/ts/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_33250) has the subclass of axiom "[has part](https://terminology.nfdi4chem.de/ts/ontologies/chebi/props?iri=http://purl.obolibrary.org/obo/BFO_0000051) some [atomic nucleus](https://terminology.nfdi4chem.de/ts/ontologies/chebi/terms?iri=http://purl.obolibrary.org/obo/CHEBI_33252)". When/if we come to define the various types of NMR spectroscopy assays using the probed nucleus as a differentiation axis, we'd probably want to do so axiomatically along the lines of: `1H NMR spectroscopy = NMR spectroscopy and ("probes" some (atomic nucleus and "part of" some hydrogen atom))`.

**Comment by tilfischer** [comment] 2024-04-09 11:40
One question I would like to add: Who serves whom?

**Comment by NRayya** [comment] 2024-08-08 15:24
As no actions were decided for this issue, it will be closed in favor of the corresponding [discussion](https://github.com/nmrML/nmrCV/discussions/27)

**Closed** 2024-08-08 15:24 UTC
